# Generated by Django 2.1.7 on 2019-03-30 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('filmName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('filmDName', models.CharField(max_length=20)),
                ('filmAName', models.CharField(max_length=45)),
                ('filmScore', models.FloatField(default=0)),
                ('image', models.ImageField(default='', upload_to='film/filmimage/')),
                ('category', models.CharField(default='动作', max_length=10)),
                ('evaluateNum', models.IntegerField(default=0, max_length=10)),
                ('showDate', models.DateField(default='1999-01-01')),
                ('deleteDate', models.DateField(default='1999-01-01')),
                ('filmSum', models.CharField(default=' ', max_length=1000)),
                ('filmScoreUser', models.CharField(default=' ', max_length=1000)),
            ],
            options={
                'ordering': ['-filmScore', 'showDate'],
            },
        ),
        migrations.CreateModel(
            name='filmscence',
            fields=[
                ('dateTime', models.DateTimeField(default='1999-01-01', primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=300)),
                ('filmName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
            ],
            options={
                'ordering': ['dateTime'],
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderId', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('filmName', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=2)),
                ('dateTime', models.DateTimeField(default='1999-01-01')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['userId', '-dateTime'],
            },
        ),
    ]
