# Generated by Django 2.1.7 on 2019-03-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('filmName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('filmDName', models.CharField(max_length=20)),
                ('filmAName', models.CharField(max_length=45)),
                ('filmScore', models.FloatField(default=0)),
                ('Route', models.CharField(max_length=20)),
                ('evaluateNum', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='filmscence',
            fields=[
                ('datatime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('seat', models.IntegerField(max_length=300)),
                ('filmName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderId', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('filmName', models.CharField(max_length=20)),
                ('seat', models.IntegerField(max_length=2)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.user'),
        ),
    ]
