# Generated by Django 2.1.7 on 2019-03-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.CharField(default='动作', max_length=10),
        ),
    ]
