# Generated by Django 2.1.7 on 2019-03-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmscence',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
