# Generated by Django 2.1.7 on 2019-03-10 03:00


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmscence',
            old_name='datatime',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='filmscence',
            name='dateTime',
            field=models.DateTimeField(default='1999-01-01', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='film',
            name='deleteDate',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='', upload_to='film/filmimage/'),
        ),
        migrations.AddField(
            model_name='film',
            name='showDate',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(default='1999-01-01'),
        ),

    ]
